/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business_Code;
import Business_Support.Utilization;
import java.sql.*;
import Exceptions.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Station Manager
 */
public class Meter_Rep_Data_Entry_Form extends javax.swing.JFrame {
    private String Con_ID;
    private String Con_Name;
    private String Old_Met_No;
    private String Old_Met_Final_Reading;
    private String Old_Met_Phase;
    private String New_Met_Phase;
    private Date Rep_Date;
    private String New_Met_No;
    private String New_Met_Initial_Reading;
    private int Vendor_Code;
    private String Rep_Purpose;
    private String Reason;
    private String Device_Category;
    private String MR_Note;
    private String Seal1="";
    private String Seal2="";
    private String Seal3="";
    private Connection conctn;
    
    
    public Meter_Rep_Data_Entry_Form()
    {
        initComponents();
    }
    /**
     * Creates new form Meter_Rep_Data_Entry_Form
     */
    public Meter_Rep_Data_Entry_Form(Connection a,String Con_Ref,Date RD,String NMN,int Vendor,String REP_P,String NMP) {
        initComponents();
        conctn=a;
        Con_Ref_Label.setText(Con_Ref);
        Con_ID=Con_Ref;
        Rep_Date=RD;
        New_Met_No=NMN;
        Vendor_Code=Vendor;
        Rep_Purpose=REP_P;
        New_Met_Phase=NMP;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Con_Ref_Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Old_Meter_No_Text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Old_Meter_Reading_Text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        New_Meter_Initial_Reading_Text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Old_Meter_Phase_Text = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Con_Name_Text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Reason_Text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Device_Cat_Text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        MR_Note_Text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Seal1_Text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Seal2_Text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Seal3_Text = new javax.swing.JTextField();
        Meter_Rep_Data_Submit_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Meter Replacement Data");
        setLocation(new java.awt.Point(300, 50));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Consumer Referece");

        jLabel2.setText("Old Meter Number*");

        jLabel3.setText("Old Meter Reading*");

        jLabel4.setText("New Meter Initial Reading*");

        New_Meter_Initial_Reading_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Meter_Initial_Reading_TextActionPerformed(evt);
            }
        });

        jLabel5.setText("Old Meter Phase");

        Old_Meter_Phase_Text.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1P", "3P" }));

        jLabel6.setText("Consumer Name");

        jLabel7.setText("Reason For Removal*");

        jLabel8.setText("Device Category*");

        jLabel9.setText("MR Note*");

        jLabel10.setText("Seal1");

        jLabel11.setText("Seal2");

        jLabel12.setText("Seal3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Con_Ref_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Con_Name_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addComponent(Old_Meter_No_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(New_Meter_Initial_Reading_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Old_Meter_Reading_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Old_Meter_Phase_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Seal3_Text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(Seal2_Text, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Seal1_Text, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MR_Note_Text, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Device_Cat_Text, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Reason_Text, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(Con_Ref_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Con_Name_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Old_Meter_No_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Old_Meter_Reading_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Old_Meter_Phase_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(New_Meter_Initial_Reading_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Reason_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Device_Cat_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MR_Note_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Seal1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Seal2_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(Seal3_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Meter_Rep_Data_Submit_.setText("Submit");
        Meter_Rep_Data_Submit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meter_Rep_Data_Submit_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Meter_Rep_Data_Submit_, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Meter_Rep_Data_Submit_)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void New_Meter_Initial_Reading_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Meter_Initial_Reading_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_Meter_Initial_Reading_TextActionPerformed

    private void Meter_Rep_Data_Submit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meter_Rep_Data_Submit_ActionPerformed
        try
        {
            Con_Name=Con_Name_Text.getText();
            Old_Met_No=Old_Meter_No_Text.getText();
            Old_Met_Final_Reading=Old_Meter_Reading_Text.getText();
            Old_Met_Phase=Old_Meter_Phase_Text.getSelectedItem().toString();
            New_Met_Initial_Reading=New_Meter_Initial_Reading_Text.getText();
            Reason=Reason_Text.getText();
            Device_Category=Device_Cat_Text.getText();
            MR_Note=MR_Note_Text.getText();
            Seal1=Seal1_Text.getText();
            Seal2=Seal2_Text.getText();
            Seal3=Seal3_Text.getText();
            if(Old_Met_No.length()==0 || Old_Met_Final_Reading.length()==0 || New_Met_Initial_Reading.length()==0 || Reason.length()==0 || Device_Category.length()==0 || MR_Note.length()==0)
            {
                throw new BlankFieldError(" * Marked Fields Are Mandatory ");
            }
            PreparedStatement pst;
            ResultSet rst=null;
            String sql="INSERT INTO METER_MOVEMENT.METER_REP_DATA VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conctn.prepareCall(sql);
            pst.setString(1,Con_ID);
            pst.setString(2,Con_Name);
            pst.setString(3,Old_Met_No);
            pst.setString(4,Old_Met_Final_Reading);
            pst.setString(5,Old_Met_Phase);
            pst.setDate(6,Rep_Date);
            pst.setString(7,New_Met_No);
            pst.setString(8,New_Met_Initial_Reading);
            pst.setString(9,New_Met_Phase);
            pst.setInt(10,Vendor_Code);
            pst.setString(11,Rep_Purpose);
            pst.setString(12, Reason);
            pst.setString(13, Device_Category);
            pst.setString(14, MR_Note);
            pst.setString(15, Seal1);
            pst.setString(16,Seal2);
            pst.setString(17,Seal3);
            pst.execute();
            pst.close();
            if(Utilization.utilizeDevice(conctn, New_Met_No, New_Met_Phase, Con_ID, Vendor_Code, Rep_Date, Rep_Purpose))
            {
                JOptionPane.showMessageDialog(rootPane, "Device Utilized Successfully", "Success", JOptionPane.PLAIN_MESSAGE);
                Con_Name_Text.setText(" ");
                Old_Meter_No_Text.setText(" ");
                Old_Meter_Reading_Text.setText(" ");;
                New_Meter_Initial_Reading_Text.setText(" ");
                Con_Ref_Label.setText(" ");
                Reason_Text.setText("");
                Device_Cat_Text.setText("");
                MR_Note_Text.setText("");
                Seal1_Text.setText("");
                Seal2_Text.setText("");
                Seal3_Text.setText("");
           }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Meter_Rep_Data_Submit_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meter_Rep_Data_Entry_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meter_Rep_Data_Entry_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meter_Rep_Data_Entry_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meter_Rep_Data_Entry_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meter_Rep_Data_Entry_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Con_Name_Text;
    private javax.swing.JLabel Con_Ref_Label;
    private javax.swing.JTextField Device_Cat_Text;
    private javax.swing.JTextField MR_Note_Text;
    private javax.swing.JButton Meter_Rep_Data_Submit_;
    private javax.swing.JTextField New_Meter_Initial_Reading_Text;
    private javax.swing.JTextField Old_Meter_No_Text;
    private javax.swing.JComboBox<String> Old_Meter_Phase_Text;
    private javax.swing.JTextField Old_Meter_Reading_Text;
    private javax.swing.JTextField Reason_Text;
    private javax.swing.JTextField Seal1_Text;
    private javax.swing.JTextField Seal2_Text;
    private javax.swing.JTextField Seal3_Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
